#!/bin/sh
# contributed by Marcel <user04113@softhome.net>, 2004.
# 
# Note: This is a sample administration script with reduced functionality
# if you are looking for more advanced features please download and configure
# 'oinkmaster' (also available as a Debian package)
#
# Example cron-entry:
#
# 7 0 * * * test -r /usr/local/bin/snort-update && /usr/local/bin/snort-update
#

vers=snapshot-2.3
#vers=snapshot-CURRENT
# get your snort code at www.snort.org & uncomment this
#oinkcode=""

[ -z "`which wget 2>/dev/null`" ] && { echo "Cannot find wget which is required for this script" >&2; exit 1; }
[ -z "$oinkcode" ] && { echo "No oinkcode defined, please configure it in $0" >&2 ; exit 1; }

/etc/init.d/snort stop
pushd /tmp
wget http://www.snort.org/pub-bin/oinkmaster.cgi/${oinkcode}/snortrules-${vers}.tar.gz && ( \
	tar zxf snortrules-${vers}.tar.gz; \
	test "$vers" == "snapshot-2_1" && rm rules/netbios.rules; \
	mv rules/*.rules /etc/snort/rules/; \
	rm rules/snort.conf; \
	mv rules/* /etc/snort/; \
	rmdir rules; \
	rm snortrules-${vers}.tar.gz; \
	chown -R root.root /etc/snort/*; \
)
popd
/etc/init.d/snort start
