.Dd January 3, 1999
.Dt SNORT-STAT 8
.Os Gnu/Linux
.Sh NAME
.Nm snort-stat
.Nd generates statistic of scans detected by snort
.Sh SYNOPSIS
.Nm cat /var/log/snort/alert.log | /usr/sbin/snort-stat 
[\fI-drfha] [\fI-t threshold] [\fI-l number]\fR 
.Sh DESCRIPTION
.Nm snort-stat
is a small script that generates a nice statistic on the port scans that
were detected by snort and reported via /var/log/snort/alert.log.
The output of this script is mailed to a user that is setup in 
/etc/snort/snort.debian.conf.
The cron script /etc/cron.daily/5snort uses this script.
.Sh OPTIONS
There are several arguments that modify the default behaviour of the program.
.Bl -tag -width aaaallexportfoo -offset indent
.It -d
Produce debugging output
.It -r
Resolve IP addresses to domain names. This might cause the script to run
slower if there are too many alerts. \fBSnort-stat\fR will timeout requests
if there is no answer in three seconds.
.It -f
Use fixed rather than variable width columns.
.It -h
Generate HTML output.
.It -t
Set a threshold for the statistics. If the number of alerts in the logfile
being analysed are not higher than the threshold no report will be generated.
The default value is 0.
.It -a
Scan the whole alert file, do not limit the analysis to a single day.
.It -l
Limit the report so that it will not generate more lines that the
defined value. The default limit is set to 99999.
.El
.Sh SEE ALSO
.Xr snort 8
.Sh AUTHORS
The script is mostly based on the snort-stat from Yen-Ming Chen <chenym+@CMU.EDU>.
The hostname resolving, the big shrinkage and this manpage were done by 
Christian Hammers <ch@debian.org>.
